### ISSUE TITLE
Load ELF DYN(.so file) cause Segmentation fault

### ISSUE THREAD

**Issue by nk4z0u** [MikhailProg/elf#10]
As the README says, "It can load static and dynamically linked ELF EXEC and DYN (pie) binaries.". If I understand correctly, ELF DYN means a .so file.

However, when I try to load a easy test so file, the program causes crash.

The [attachment](https://github.com/user-attachments/files/16186249/crash.zip) is the source code of test so file, and the compiled so file, when I call `./loader /path/to/libtestso.so`, it causes crash.

Does the project support to load a so file, or it is indeed a bug?

Thank you.

**Comment by nk4z0u** [comment]
Seems my understanding is mistake, if a executable is compiled with -fPIC, it will also be Identified as ET_DYN.

After I read the source code, seems the project can only load executable file but not .so file.

**Comment by MikhailProg** [comment]
> As the README says, "It can load static and dynamically linked ELF EXEC and DYN (pie) binaries.". If I understand correctly, ELF DYN means a .so file.
> 

DYN means the type of ELF, you can get DYN with -pie and -pic options, for loader there is no difference how the binary was compiled and it can load both. .so file has garbage entry point (since there is no entry point in shared library, actually you can specify it with -e option but you should bootstrap libc manually if you use libc inside or your entry should be lightweight) that causes segfault at calling entry point from ELF header. As an option you can comment calling trampo and provide your own logic after .so is placed into memory.
